package ProjectEulerJava;

import org.junit.Test;

import javax.swing.text.html.HTMLDocument;
import java.text.MessageFormat;
import java.util.Iterator;
import java.util.List;
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

//Each new term in the Fibonacci sequence is generated by adding the previous
//two terms. By starting with 1 and 2, the first 10 terms will be:
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.

public class Problem2 {
    public static void main(String[] args) {
        System.out.println(MessageFormat.format("Sum: {0}", solver()));
    }

    public static long solver() {
        return Stream.iterate(new long[]{1, 2}, f -> new long[]{f[1], f[0] + f[1]})
                .mapToLong(f->f[0])
                .limit(10)
                .sum()
                ;
        // 233168
    }
}
